<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PipelineControl.Drivers.Abstractions\PipelineControl.Drivers.Abstractions.csproj" />
    <ProjectReference Include="..\PipelineControl.Shared\PipelineControl.Shared.csproj" />
  </ItemGroup>

</Project>
